// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package hostinfo

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatConfig is an auto-generated flat version of Config.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatConfig struct {
}

// FlatMapstructure returns a new FlatConfig.
// FlatConfig is an auto-generated flat version of Config.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Config) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatConfig)
}

// HCL2Spec returns the hcl spec of a Config.
// This spec is used by HCL to read the fields of Config.
// The decoded values from this spec will then be applied to a FlatConfig.
func (*FlatConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{}
	return s
}

// FlatDatasourceOutput is an auto-generated flat version of DatasourceOutput.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatDatasourceOutput struct {
	OsType       *string `mapstructure:"os_type" cty:"os_type" hcl:"os_type"`
	Version      *string `mapstructure:"version" cty:"version" hcl:"version"`
	Architecture *string `mapstructure:"architecture" cty:"architecture" hcl:"architecture"`
	Platform     *string `mapstructure:"platform" cty:"platform" hcl:"platform"`
	Family       *string `mapstructure:"family" cty:"family" hcl:"family"`
}

// FlatMapstructure returns a new FlatDatasourceOutput.
// FlatDatasourceOutput is an auto-generated flat version of DatasourceOutput.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*DatasourceOutput) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatDatasourceOutput)
}

// HCL2Spec returns the hcl spec of a DatasourceOutput.
// This spec is used by HCL to read the fields of DatasourceOutput.
// The decoded values from this spec will then be applied to a FlatDatasourceOutput.
func (*FlatDatasourceOutput) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"os_type":      &hcldec.AttrSpec{Name: "os_type", Type: cty.String, Required: false},
		"version":      &hcldec.AttrSpec{Name: "version", Type: cty.String, Required: false},
		"architecture": &hcldec.AttrSpec{Name: "architecture", Type: cty.String, Required: false},
		"platform":     &hcldec.AttrSpec{Name: "platform", Type: cty.String, Required: false},
		"family":       &hcldec.AttrSpec{Name: "family", Type: cty.String, Required: false},
	}
	return s
}
